source = ~/.config/hypr/config/monitors.conf
source = ~/.config/hypr/config/decorations.conf
source = ~/.config/hypr/config/animations.conf
source = ~/.config/hypr/config/layouts.conf
source = ~/.config/hypr/config/misc.conf
source = ~/.config/hypr/config/input.conf
source = ~/.config/hypr/config/keybinds.conf
source = ~/.config/hypr/config/windowrules.conf
