import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[font]
size = 10.0

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[env]
TERM = "xterm-256color"
